apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: ppclaim-too-db
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: ppclaim
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: ppclaim-too
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: petclinic-db-claim-too
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: ppclaim-too

